require.config({
  //baseUrl: 'js/',
	waitSeconds:0,

  // alias libraries paths.  Must set 'angular'
  paths: {
    'angular': '/enterprise/js/libs/angular/angular.min',
    'angular-route': '/enterprise/js/libs/angular-route/angular-route.min',    
    'angularAMD': '/enterprise/js/libs/angularAMD/angularAMD.min',
    'ngload': '/enterprise/js/libs/angularAMD/ngload.min',
    'angular-ui-bootstrap': '/enterprise/js/libs/angular-ui/angular-bootstrap/ui-bootstrap-tpls.min',
    'angular-ui-router': '/enterprise/js/libs/angular-ui/angular-ui-router/angular-ui-router.min',
    'angular-strap': '/enterprise/js/libs/angular-strap/angular-strap.min',
    'angular-strap-tpl': '/enterprise/js/libs/angular-strap/angular-strap.tpl.min',
    'angular-animate': '/enterprise/js/libs/angular-animate/angular-animate.min',
    'restangular': '/enterprise/js/libs/restangular/restangular.min',
    'ng-table': "/enterprise/js/libs/ng-table/ng-table",
    'ng-file-upload-shim': "/enterprise/js/libs/ng-file-upload/ng-file-upload-shim.min",
    'ng-file-upload': "/enterprise/js/libs/ng-file-upload/ng-file-upload.min",
    'underscore': "/enterprise/js/libs/restangular/underscore.min",
    'angular-ui-tree': '/enterprise/js/libs/angular-ui/angular-ui-tree/angular-ui-tree.min',
    'lodash': "/enterprise/js/libs/restangular/lodash.min",
    'angular-locale_zh' : '/enterprise/js/libs/angular-locale/angular-locale_zh.min',
    'jquery': '/enterprise/js/libs/jquery/jquery-1.12.3.min',
    'jquery-scroll': '/enterprise/js/libs/jquery-scroll/jquery-scroll',
    'ng-file-upload-shim': "/enterprise/js/libs/ng-file-upload/ng-file-upload-shim",
    'ng-file-upload': "/enterprise/js/libs/ng-file-upload/ng-file-upload",
    'ng-table': "/enterprise/js/libs/ng-table/ng-table.min",
    'util':'/enterprise/js/libs/calender/util',
    'week':'/enterprise/js/libs/calender/week',
    'month':'/enterprise/js/libs/calender/month',
    'calendar_base':'/enterprise/js/libs/calender/calendar_base',
    'calendar':"/enterprise/js/libs/calender/calendar.min",
    'day_week_month':"/enterprise/js/libs/calender/day_week_month",
    'angular-sanitize': 'libs/angular-strap/angular-sanitize.min',
    'highchart':"libs/highcharts/highcharts.src.min",
    'customUtilJS': '/enterprise/js/customUtilJS',
    'jquery.ztree.core-3.5': 'libs/zTreeJS/jquery.ztree.core-3.5',
    'jquery.ztree.excheck-3.5': 'libs/zTreeJS/jquery.ztree.excheck-3.5',
    'jquery.ztree.exedit-3.5': 'libs/zTreeJS/jquery.ztree.exedit-3.5'
  },

  // Add angular modules that does not support AMD out of the box, put it in a shim
  shim: {
	'angular' : {
		exports: 'angular'
	},
    'angular-route': [ 'angular' ],
    'angularAMD': [ 'angular' ],
    'angular-locale_zh':['angular'],
    'ngload': [ 'angularAMD' ],
    'angular-ui-bootstrap': [ 'angular' ],
    'angular-ui-router': [ 'angular' ],
    'restangular': ['angular', 'underscore', 'lodash'],
    'angular-animate': ['angular'],
    'angular-sanitize':['angular'],
    'angular-strap': ['angular', 'angular-animate'],
    'angular-strap-tpl': ['angular-strap'],
    'angular-ui-tree' : ['angular'],
    'jquery-scroll': [ 'jquery'],
    'ng-table': [ 'angular'],
    'highchart':['jquery'],
    'util':['jquery'],
    'week':['jquery','util'],
    'month':['jquery','util'],
    'day_week_month':['jquery','util'],
    'calendar_base':['jquery','util'],
    'calendar':['jquery','util'],
    'ng-file-upload-shim': [ 'angular' ],
    'ng-file-upload': [ 'angular' ],
    'jquery.ztree.core-3.5': [ 'jquery' ],
    'jquery.ztree.excheck-3.5': [ 'jquery.ztree.core-3.5' ],
    'jquery.ztree.exedit-3.5': [ 'jquery.ztree.excheck-3.5' ],
    'customUtilJS': [ 'jquery' ]
  },
  deps: ['app']
});
