define({
	//public
	"status": "Status",
	"calcStatus": "Calculated state",
	"search": "Search",
	"creator": "Create person",
	"createTime": "Creation time",
	"reset": "Reset",
	"operation": "Operation",
	"edit": "edit",
	"toDelete": "delete",
	"log": "log",
	"lookUp": "Look up",
	"pleaseSelect": "Please select",
	"pleaseInput": "Please input",
	"save": "Save",
	"noSave":"No save",
	"cancel": "Cancel",
	"buildJson": "Generate JSON",
	"recalculate": "Recalculation",
	"describe":"describe",
	"noData":"No data",
	"remove":"Remove",
	"rename":"Rename",
	"confirmDelete":"Sure you want to delete",
	
	
	//标签定义--html
	"addBasicTag":"Add basic tag",
	"editBasicTag":"Edit basic tag",
	"labelDefinition": "Add basic tag",
	"tagName": "Tag name",
	"touchPointTypes": "Population type",
	"tagSources": "Label source",
	"tagType": "Tag type",
	"changeTagDataTime": "Population update time",
	"allTags": "All tags",
	"backTagList": "Return basic tag list",
	"tagNameMaxLength": "Tag name supports up to 256 characters",
	"tagCategory": "Tag category",
	"uiData": "UI data",
	"serverData": "Server data",
	"searchCritera": "Search criteria",
	"inputKeyword": "Please enter a keyword",
	"populationAttributes": "Population attributes",
	//js
	"noPowerDelOtherTags": "You do not have permission to delete the label created by others.",
	"inputTypeName": "Enter a category name",
	"labelDefinitionList": "Basic Tag definition list",
	"confirmDelTags": "Be sure to delete Tags",
	"addTagSuccess": "Label add success",
	"editTagSuccess": "Label editing success",
	"inputTagName": "Please enter a label name",
	"createCrowdAttrOrHavior": "Create a population attribute or crowd behavior condition",
	"onlyZmSzXhx": "Only letters, numbers, and underscores.",
	"tagRecalculateSuccess": "Tag initiates to re calculate the success",
	"tagRecalculateConfirms": "Tag has changed,do you want to save the changes before recalculation?",
	
	//业务标签--html
	"businessTagList":"Business tag list",
	"businessTagName":"Business tag name",
	"backBusinessTagList":"Return business tag list",
	"viewBusinessTag":"View business tag",
	"addBusinessTag":"Add business tag",
	"editBusinessTag":"Edit business tag",
	"businessTagNameRequire":"Business tag name supports up to 256 characters",
	"createBusinessTag": "Please create the conditions for the business tag.",
	
	//系统标签--html
	"systemTagList":"System tag list",
	"addSystemTag":"Add system tag",
	"systemTagName":"System Tag Name",
	"backSystemTagList":"Return system tags",
	"viewSysTemTag":"View system tag",
	"addSystemTag":"Add system tag",
	"editSystemTag":"Edit system tag",
	"systemTagNameRequire":"System tag name supports up to 256 characters",
	"selectTouchPointTypes":"Please select the type of crowd",
	"calculationScript":"Calculation script",
	"selectCalculationScript":"Please select the calculation script",
	"operatingParameters":"Operating parameters",
	"scriptParamRequire":'Note: the script must be placed on the TD Batch Executor machine, and Executor has permission to access the script file (including the file directory and file that the script will access) (Manager) Script parameters: -a #${paramName1}# -b #{paramName2}#, parameters do not appear"".',
	"inputOperatingParameters":"Please enter operating parameters",
	"describeRequire":"Description supports up to 512 characters",
	//js
	"confirmDelSysTags":"Identify the system labels to be deleted",
	"noRecalculate":"Task is executing, cannot recalculate",
	"systemTagAddSuccess":"System tab to add success",
	"systemTagEditSuccess":"System label editing success",
	"inputSystemTagName":"Please enter the system label name",
	"countingAgainLater":"Re counting, please try again later",
	"systemTagCalcuSuccess":"System tag initiated recalculation success",
	
	//标签分类--html
	"removeTag":"Remove Tag",
	"classification":"Classification",
	"tagClassification":"Tag classification",
	"basicInfo":"Basic information",
	"categoryName":"Category name",
	"numberOfSubCategories":"Number of sub categories",
	"tagNumber":"Tag number",
	"classTagPercentage":"Class label percentage",
	"percentageOfSubTag":"Percentage of sub label",
	"tag":"Tag",
	"addTag":"Add tag",
	"currentClassification":"Current classification",
	"selectedTags":"Selected tags",
	"selectTag":"Select tag",
	"tagNamePrompt":"Please enter the label name, enter the end can enter confirmation",
	"addCategory":"Add category",
	"editCategory":"Edit category",
	"categoryParent":"Category parent",
	"selectCategoryParent":"Please select the superior classification",
	"categoryNameUp12":"Category name supports up to 12 characters",
	"inputCategoryName":"Please enter a category name",
	//js
	"categoryNameIsEmpty":"Category name cannot be empty, please re-enter",
	"netWorkUngelivable":"Network ungelivable,please try again later",
	"canNotDelete":"Can not delete, please delete first",
	"subCategory":"sub ategory",
	"selectUp20":"Select up to 20 tabs at a time, save and then operate",
	"noRepeatAddTag":"This tag has been added and cannot be added repeatedly",
	"noCheckedTag":"This label is not checked, please re-enter",
	"selectTagThanSave":"Please select the label and then save",
	"confirmRemoveTagFromCategory":"Make sure to remove labels from the current category",
	"selectTagThanRemove":"Please select tag and then remove",
	"removeTagSuccess":"Congratulations, successfully removed tag",
	"selectRemoveTag":"Select a category to remove tags",
	"newSubCategory":"New-build sub category",
	"existingCanNotDel":"Existing subcategory or label, cannot be deleted!",
	"nodeNameNoEmpty":"The node name cannot be empty",
	"editFailNodeNameNoRepeat":"Failed to edit, node name of the same level can not repeat",
	
	//TODO:项目整体国际化完成后删除
	"todo": "todo"
});